### ISSUE TITLE
Clarification on open tracing and zipkin

### ISSUE THREAD

**Issue by Moocar** [honeycombio/honeycomb-opentracing-proxy#21]
Hi there,

I'm [adding tracing support](https://github.com/gatsbyjs/gatsby/issues/1074) to a react static site generator called Gatsby. We were going to instrument the codebase with open tracing so that we could plugin many tracing backends. I was happy to see that honeycomb supports open tracing via this proxy. 

I'm a little confused though. This proxy is a zipkin proxy, not an open tracing proxy (since open tracing is simply a language level spec). And Zipkin is [no longer an open tracing supported platform](https://github.com/opentracing/opentracing.io/issues/258). In addition, there are no official javascript zipkin open tracing libraries.

So, what is the recommendation on how to send traces to honeycomb from javascript? Is it to ignore open tracing and just use [zipkin-js](https://github.com/openzipkin/zipkin-js)? If not, are there plans for a future honeycomb open tracing js library?

We'd really love to enable honeycomb as a tracing backend :)

**Comment by emfree** [comment]
Hi there, sorry for the delayed response. And also sorry for the confusion here. Reading between the lines of https://github.com/gatsbyjs/gatsby/issues/1074, it looks like you've been able to make this work using zipkin-javascript-opentracing -- is that correct, and is there anything else we can do to help you be successful?

Several people have now pointed out that the name of this project is confusing, and well, I can't disagree. A little bit of background: In practice, OpenTracing library _implementation_ specifies two things:
- a trace wire format: how to transmit span data to a backend
- a propagation format: how to carry trace context between different services.

Rather than shipping our own suite of OpenTracing-compatible client libraries, our goal with this project was to try to provide a translation layer between _established_ trace wire formats and the Honeycomb API. The Zipkin wire format is arguably the most prevalent, and hence it's what we chose to implement first. Importantly, that makes it easier to work with trace data that comes from services such as [Envoy](https://www.envoyproxy.io/), which already have built-in Zipkin support. But we would certainly be open to adding support for other wire formats as well.

Many Zipkin client libraries _are_ OpenTracing-compatible, but as you point out that's not always true, and we were wrong to try to conflate the two. Perhaps `honeycomb-tracing-proxy` would have been a better name here -- we'll noodle on ways to clarify this (ideally without a disruptive renaming :grimacing: ).

Thanks again. Please let us know if you have any other feedback or if there's anything else we can do to help.

**Comment by Moocar** [comment]
Thanks for the well thought out response. You are correct that we've got everything working using `zipkin-javascript-opentracing` which is an effective way to transport spans up to Honeycomb. 

I think re-using the zipkin wire format is a great move. The naming is a bit confusing, but now that you've clarified the history, I can live with it :)

Thanks!
