### ISSUE TITLE
Support Span Logs

### ISSUE THREAD

**Issue by kpruden** [honeycombio/honeycomb-opentracing-proxy#32]
Currently the proxy handles OT log events by adding the event's attributes to the parent span. This is semantically incorrect as a log event represents a thing that happened at a specific instance (an error, say), vs a span which represents something with a duration. This implementation loses the timestamp of the log event(s)

Further, if a single span has more than one log event with the same attributes, only the values from the last such event will be set on the span.

Ideally log events would show up as distinct events in HC, with a parent span and timestamp, but no duration. These events should appear in the trace UI, although it's not clear to me how they should be displayed, as they have no duration...

**Comment by will-sargent-eero** [comment]
Losing information on multiple logging statements is not good at all.

**Comment by akvanhar** [comment]
This will be fixed in Honeycomb's OpenTelemetry exporter https://github.com/honeycombio/opentelemetry-exporter-go/blob/master/honeycomb/honeycomb.go#L198

They will be visualized in the Trace sidebar like this (Note: this is currently in Alpha)
![image](https://user-images.githubusercontent.com/10929533/67430050-4d29df00-f596-11e9-9e1e-51e8058a82e4.png)

OpenTelemetry will implement an OpenTracing bridge.

**Comment by bdarfler** [comment]
As per the README "This project is not actively maintained and you should not use it. New issues and pull requests will likely be ignored. OpenTracing has been superseded by OpenTelementry."

We are now closing all pull requests and issues and archiving the repo.
